/************************************************************************************

Depthkit Unity SDK License v1
Copyright 2016-2024 Simile Inc dba Scatter. All Rights reserved.  

Licensed under the the Simile Inc dba Scatter ("Scatter")
Software Development Kit License Agreement (the "License"); 
you may not use this SDK except in compliance with the License, 
which is provided at the time of installation or download, 
or which otherwise accompanies this software in either electronic or hard copy form.  

You may obtain a copy of the License at http://www.depthkit.tv/license-agreement-v1

Unless required by applicable law or agreed to in writing, 
the SDK distributed under the License is distributed on an "AS IS" BASIS, 
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
See the License for the specific language governing permissions and limitations under the License. 

************************************************************************************/

#pragma kernel GaussianBlurFilter1 TILE_BORDER=1
#pragma kernel GaussianBlurFilter2 TILE_BORDER=2
#pragma kernel GaussianBlurFilter4 TILE_BORDER=4
#pragma kernel GaussianBlurFilter8 TILE_BORDER=8
#pragma kernel GaussianBlurFilter16 TILE_BORDER=16
#pragma kernel GaussianBlurFilter32 TILE_BORDER=32


static const uint BLOCK_SIZE = 8; 

Texture2DArray<float> _PingData;
RWTexture2DArray<float> _PongData;
int _Slice;

#define DK_GAUSSIAN_FILTER_SAMPLE_UV(uv) float3(uv.xy, (float)_Slice)

#define DK_GAUSSIAN_FILTER_OUTPUT_COORD(pixel) int3(pixel.xy, _Slice)

#include "Packages/nyc.scatter.depthkit.core/Runtime/Resources/Shaders/Util/GaussianBlurFilter.cginc"

[numthreads(BLOCK_WIDTH, 1, 1)]
void GaussianBlurFilter1(uint3 id : SV_DispatchThreadID, uint3 GroupId : SV_GroupID, uint3 GroupThreadId : SV_GroupThreadID, uint GroupIndex : SV_GroupIndex)
{
    GaussianBlurFilter(id, GroupId, GroupThreadId, GroupIndex);
}

[numthreads(BLOCK_WIDTH, 1, 1)]
void GaussianBlurFilter2(uint3 id : SV_DispatchThreadID, uint3 GroupId : SV_GroupID, uint3 GroupThreadId : SV_GroupThreadID, uint GroupIndex : SV_GroupIndex)
{
    GaussianBlurFilter(id, GroupId, GroupThreadId, GroupIndex);
}

[numthreads(BLOCK_WIDTH, 1, 1)]
void GaussianBlurFilter4(uint3 id : SV_DispatchThreadID, uint3 GroupId : SV_GroupID, uint3 GroupThreadId : SV_GroupThreadID, uint GroupIndex : SV_GroupIndex)
{
    GaussianBlurFilter(id, GroupId, GroupThreadId, GroupIndex);
}

[numthreads(BLOCK_WIDTH, 1, 1)]
void GaussianBlurFilter8(uint3 id : SV_DispatchThreadID, uint3 GroupId : SV_GroupID, uint3 GroupThreadId : SV_GroupThreadID, uint GroupIndex : SV_GroupIndex)
{
    GaussianBlurFilter(id, GroupId, GroupThreadId, GroupIndex);
}

[numthreads(BLOCK_WIDTH, 1, 1)]
void GaussianBlurFilter16(uint3 id : SV_DispatchThreadID, uint3 GroupId : SV_GroupID, uint3 GroupThreadId : SV_GroupThreadID, uint GroupIndex : SV_GroupIndex)
{
    GaussianBlurFilter(id, GroupId, GroupThreadId, GroupIndex);
}

[numthreads(BLOCK_WIDTH, 1, 1)]
void GaussianBlurFilter32(uint3 id : SV_DispatchThreadID, uint3 GroupId : SV_GroupID, uint3 GroupThreadId : SV_GroupThreadID, uint GroupIndex : SV_GroupIndex)
{
    GaussianBlurFilter(id, GroupId, GroupThreadId, GroupIndex);
}
